import sympy
import helper_functions as hf

symbol_mapping = dict(
    delta_time=dict(c='dt', latex='\Delta t'),
    gravity=dict(c='g', latex='g'),
    delta_angle_x=dict(c='delta_angle_x', latex='\Delta \Omega_x'),
    delta_angle_y=dict(c='delta_angle_y', latex='\Delta \Omega_y'),
    delta_angle_z=dict(c='delta_angle_z', latex='\Delta \Omega_z'),
    delta_angle=dict(c='delta_angle', latex='\Delta \Omega'),
    delta_velocity_x=dict(c='delta_velocity_x', latex='\Delta v_x'),
    delta_velocity_y=dict(c='delta_velocity_y', latex='\Delta v_y'),
    delta_velocity_z=dict(c='delta_velocity_z', latex='\Delta v_z'),
    delta_velocity=dict(c='delta_velocity', latex='\Delta v'),
    u=dict(c='u', latex='u'),
    delta_angle_x_var=dict(c='delta_angle_x_var',
                           latex='\sigma^2_{\Delta \Omega_x}'),
    delta_angle_y_var=dict(c='delta_angle_y_var',
                           latex='\sigma^2_{\Delta \Omega_y}'),
    delta_angle_z_var=dict(c='delta_angle_z_var',
                           latex='\sigma^2_{\Delta \Omega_z'),
    delta_angle_var=dict(c='delta_angle_var',
                         latex='\sigma^2_{\Delta \Omega}'),
    delta_velocity_x_var=dict(c='delta_velocity_x_var',
                              latex='\sigma^2_{\Delta v_x}'),
    delta_velocity_y_var=dict(c='delta_velocity_y_var',
                              latex='\sigma^2_{\Delta v_y}'),
    delta_velocity_z_var=dict(c='delta_velocity_z_var',
                              latex='\sigma^2_{\Delta v_z}'),
    delta_velocity_var=dict(c='delta_velocity_var',
                            latex='\sigma^2_{\Delta v'),
    u_var=dict(c='u_var', latex='sigma^2_u'),
    qw=dict(c='qw', latex='q_w'),
    qx=dict(c='qx', latex='q_x'),
    qy=dict(c='qy', latex='q_y'),
    qz=dict(c='qz', latex='q_z'),
    q=dict(c='q', latex='q'),
    vx=dict(c='vx', latex='v_x'),
    vy=dict(c='vy', latex='v_y'),
    vz=dict(c='vz', latex='v_z'),
    v=dict(c='v', latex='v'),
    px=dict(c='px', latex='p^{ENU}_x'),
    py=dict(c='py', latex='p^{ENU}_y'),
    pz=dict(c='pz', latex='p^{ENU}_z'),
    p=dict(c='p', latex='p'),
    delta_angle_bias_x=dict(c='delta_angle_bias_x',
                            latex='\Delta \Omega_{bias, x}'),
    delta_angle_bias_y=dict(c='delta_angle_bias_y',
                            latex='\Delta \Omega_{bias, y}'),
    delta_angle_bias_z=dict(c='delta_angle_bias_z',
                            latex='\Delta \Omega_{bias, z}'),
    delta_angle_bias=dict(c='delta_angle_bias', latex='\Delta \Omega_{bias}'),
    delta_angle_true=dict(c='delta_angle_true', latex='\Delta \Omega_{true}'),
    delta_velocity_bias_x=dict(c='delta_velocity_bias_x',
                               latex='\Delta v_{bias, x}'),
    delta_velocity_bias_y=dict(c='delta_velocity_bias_y',
                               latex='\Delta v_{bias, y}'),
    delta_velocity_bias_z=dict(c='delta_velocity_bias_z',
                               latex='\Delta v_{bias, z}'),
    delta_velocity_bias=dict(c='delta_velocity_bias', latex='\Delta v_{bias}'),
    delta_velocity_true=dict(c='delta_velocity_true', latex='\Delta v_{true}'),
    state=dict(c='state', latex='x'),
    q_new=dict(c='q_new', latex='q_{k+1}'),
    v_new=dict(c='v_new', latex='v_{k+1}'),
    p_new=dict(c='p_new', latex='p_{k+1}'),
    delta_angle_bias_new=dict(c='delta_angle_bias_new',
                              latex='\Delta \Omega_{bias, k+1}'),
    delta_velocity_bias_new=dict(c='delta_velocity_bias_new',
                                 latex='\Delta v_{bias, k+1}'),
    state_new=dict(c='state_new', latex='x_{k+1}'),
    F=dict(c='F', latex='F'),
    G=dict(c='G', latex='G'),
    Q=dict(c='Q', latex='Q'),
    P=dict(c='P', latex='P'),
    P_new=dict(c='P_new', latex='P_{k+1}'),
    P_new_simplified(c='P_new_simplified', latex='P_{k+1,simplified}'),
)
dt = sympy.Symbol
